# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青看点

on:
  workflow_dispatch:
  schedule:
     - cron: '*/12 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
        YOUTH_HEADER2: ${{ secrets.YOUTH_HEADER2 }}
        YOUTH_ARTBODY2: ${{ secrets.YOUTH_ARTBODY2 }}
        YOUTH_REDBODY2: ${{ secrets.YOUTH_REDBODY2 }}
        YOUTH_TIME2: ${{ secrets.YOUTH_TIME2 }}
        YOUTH_HEADER3: ${{ secrets.YOUTH_HEADER3 }}
        YOUTH_ARTBODY3: ${{ secrets.YOUTH_ARTBODY3 }}
        YOUTH_REDBODY3: ${{ secrets.YOUTH_REDBODY3 }}
        YOUTH_TIME3: ${{ secrets.YOUTH_TIME3 }}
    steps:
      - name: Checkout
        run: |
          
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          cd ~/Scripts
          npm install
      - name: '运行 【中青看点】'
        if: env.YOUTH_HEADER
        run: |
          cd ~/Scripts
          node Task/youth.js
          
       env:
        YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

      - name: '运行 【中青看点二】'
        if: env.YOUTH_HEADER2
        run: |
          cd ~/Scripts
          node Task/youth.js
       env:
        YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【中青看点三】'
        if: env.YOUTH_HEADER3
        run: |
          cd ~/Scripts
          node Task/youth.js
          
        env:
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
